# The name of our service, used in the name of resources such as the CloudFormation stack.
service: serverless-demo-june-2019

# We are using two plugins to illustrate how Serverless framework plugins work.
plugins:
  - serverless-api-stage
  - serverless-plugin-typescript

# These settings are used by the serverless-api-stage plugin.
custom:
  stage: ${self:provider.stage}
  stageSettings:
    LoggingLevel: INFO

# AWS-specific configuration, used as defaults for all functions.
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-southeast-2
  environment:
    NODE_ENV: ${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource:
        - Fn::GetAtt: [ ReportsTable, Arn ]
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource: '*'

# Our functions and the events that are configured to invoke them.
functions:
  listReports:
    handler: src/handlers/http/reports.list
    events:
      - http:
          path: reports/{category}
          method: get
          cors: true
  createReport:
    handler: src/handlers/http/reports.create
    events:
      - http:
          path: reports/{category}
          method: post
          cors: true
  reportsInserted:
    handler: src/handlers/dynamodb/reports.inserted
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [ ReportsTable, StreamArn ]

# Additional resources; this is standard CloudFormation.
# In this case we are creating a DynamoDB table with a stream.
resources:
  Resources:
    ReportsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: reports_${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: categoryId
            AttributeType: S
          - AttributeName: eventTimestamp
            AttributeType: N
        KeySchema:
          - KeyType: HASH
            AttributeName: categoryId
          - KeyType: RANGE
            AttributeName: eventTimestamp
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE

# For more information, see https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/
